"""enrich_pattern_data

Revision ID: a4ccd43dcf94
Revises: 0006_increase_embedding_dimension
Create Date: 2026-04-10 17:55:09.829546
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a4ccd43dcf94'
down_revision: Union[str, None] = '0006_increase_embedding_dimension'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patterns', sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patterns', sa.Column('core_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patterns', sa.Column('observed_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patterns', sa.Column('root_causes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patterns', sa.Column('resolution_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patterns', sa.Column('evidence_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patterns', 'evidence_summary')
    op.drop_column('patterns', 'resolution_steps')
    op.drop_column('patterns', 'root_causes')
    op.drop_column('patterns', 'observed_errors')
    op.drop_column('patterns', 'core_entities')
    op.drop_column('patterns', 'trigger_conditions')
    # ### end Alembic commands ###
