"""add_on_delete_cascade_to_correlations

Revision ID: b70b9f09bf1f
Revises: b087c10d602a
Create Date: 2026-04-22 16:31:43.433582
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b70b9f09bf1f'
down_revision: Union[str, None] = 'b087c10d602a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Attachment Artifacts
    op.drop_constraint('attachment_artifacts_evidence_id_fkey', 'attachment_artifacts', type_='foreignkey')
    op.create_foreign_key(None, 'attachment_artifacts', 'evidence_items', ['evidence_id'], ['id'], ondelete='CASCADE')
    
    # 2. Case Links
    op.drop_constraint('case_links_evidence_id_fkey', 'case_links', type_='foreignkey')
    op.create_foreign_key(None, 'case_links', 'evidence_items', ['evidence_id'], ['id'], ondelete='CASCADE')
    
    # 3. Correlation Edges
    op.drop_constraint('correlation_edges_target_evidence_id_fkey', 'correlation_edges', type_='foreignkey')
    op.drop_constraint('correlation_edges_source_evidence_id_fkey', 'correlation_edges', type_='foreignkey')
    op.create_foreign_key(None, 'correlation_edges', 'evidence_items', ['target_evidence_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'correlation_edges', 'evidence_items', ['source_evidence_id'], ['id'], ondelete='CASCADE')
    
    # 4. Episode Steps
    op.drop_constraint('episode_steps_episode_id_fkey', 'episode_steps', type_='foreignkey')
    op.create_foreign_key(None, 'episode_steps', 'episodes', ['episode_id'], ['id'], ondelete='CASCADE')

    # 5. Pattern Evidence Links
    op.drop_constraint('pattern_evidence_links_episode_id_fkey', 'pattern_evidence_links', type_='foreignkey')
    op.create_foreign_key(None, 'pattern_evidence_links', 'episodes', ['episode_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pattern_evidence_links', type_='foreignkey')
    op.create_foreign_key('pattern_evidence_links_episode_id_fkey', 'pattern_evidence_links', 'episodes', ['episode_id'], ['id'])
    op.drop_constraint(None, 'episode_steps', type_='foreignkey')
    op.create_foreign_key('episode_steps_episode_id_fkey', 'episode_steps', 'episodes', ['episode_id'], ['id'])
    op.drop_constraint(None, 'correlation_edges', type_='foreignkey')
    op.drop_constraint(None, 'correlation_edges', type_='foreignkey')
    op.create_foreign_key('correlation_edges_source_evidence_id_fkey', 'correlation_edges', 'evidence_items', ['source_evidence_id'], ['id'])
    op.create_foreign_key('correlation_edges_target_evidence_id_fkey', 'correlation_edges', 'evidence_items', ['target_evidence_id'], ['id'])
    op.drop_constraint(None, 'case_links', type_='foreignkey')
    op.create_foreign_key('case_links_evidence_id_fkey', 'case_links', 'evidence_items', ['evidence_id'], ['id'])
    op.drop_constraint(None, 'attachment_artifacts', type_='foreignkey')
    op.create_foreign_key('attachment_artifacts_evidence_id_fkey', 'attachment_artifacts', 'evidence_items', ['evidence_id'], ['id'])
    # ### end Alembic commands ###

