export const NODE_TYPE_OPTIONS = [
  "pattern",
  "episode",
  "playbook",
  "evidence",
  "identity",
  "trigger",
  "entity",
  "error",
  "root_cause",
  "session",
  "execution_run",
  "approval_request",
  "user",
  "decision",
  "decision_option",
  "decision_outcome",
  "tenant_policy",
  "action_policy",
  "claim",
  "error_signature",
  "fix_pattern",
  "case_outcome",
  "entity_term",
] as const;

export const MAF_NODE_TYPE_OPTIONS = [
  "session",
  "decision",
  "decision_option",
  "decision_outcome",
  "approval_request",
  "execution_run",
  "playbook",
  "pattern",
  "episode",
  "evidence",
  "identity",
  "entity",
  "user",
  "tenant_policy",
  "action_policy",
  "claim",
  "error_signature",
  "fix_pattern",
  "case_outcome",
] as const;

export const nodeColors: Record<
  string,
  { bg: string; border: string; text: string; dot: string }
> = {
  pattern:    { bg: "bg-indigo-900",  border: "border-indigo-500",  text: "text-white",       dot: "bg-indigo-500" },
  episode:    { bg: "bg-purple-900",  border: "border-purple-500",  text: "text-slate-100",   dot: "bg-purple-500" },
  playbook:   { bg: "bg-sky-900",     border: "border-sky-500",     text: "text-sky-100",     dot: "bg-sky-500" },
  identity:   { bg: "bg-teal-900",    border: "border-teal-500",    text: "text-teal-100",    dot: "bg-teal-500" },
  evidence:   { bg: "bg-slate-800",   border: "border-slate-500",   text: "text-slate-100",   dot: "bg-slate-500" },
  trigger:    { bg: "bg-amber-900",   border: "border-amber-500",   text: "text-amber-100",   dot: "bg-amber-500" },
  entity:     { bg: "bg-emerald-900", border: "border-emerald-500", text: "text-emerald-100", dot: "bg-emerald-500" },
  error:      { bg: "bg-rose-900",    border: "border-rose-500",    text: "text-rose-100",    dot: "bg-rose-500" },
  root_cause:        { bg: "bg-orange-900",  border: "border-orange-500",  text: "text-orange-100",  dot: "bg-orange-500" },
  session:           { bg: "bg-cyan-900",    border: "border-cyan-500",    text: "text-cyan-100",    dot: "bg-cyan-500" },
  execution_run:     { bg: "bg-lime-900",    border: "border-lime-500",    text: "text-lime-100",    dot: "bg-lime-500" },
  approval_request:  { bg: "bg-yellow-900",  border: "border-yellow-500",  text: "text-yellow-100",  dot: "bg-yellow-500" },
  user:              { bg: "bg-fuchsia-900", border: "border-fuchsia-500", text: "text-fuchsia-100", dot: "bg-fuchsia-500" },
  decision:          { bg: "bg-amber-900",   border: "border-amber-400",   text: "text-amber-100",   dot: "bg-amber-400" },
  decision_option:   { bg: "bg-yellow-900",  border: "border-yellow-400",  text: "text-yellow-100",  dot: "bg-yellow-400" },
  decision_outcome:  { bg: "bg-orange-900",  border: "border-orange-400",  text: "text-orange-100",  dot: "bg-orange-400" },
  tenant_policy:     { bg: "bg-violet-900",  border: "border-violet-500",  text: "text-violet-100",  dot: "bg-violet-500" },
  action_policy:     { bg: "bg-blue-900",    border: "border-blue-400",    text: "text-blue-100",    dot: "bg-blue-400" },
  claim:             { bg: "bg-pink-900",    border: "border-pink-400",    text: "text-pink-100",    dot: "bg-pink-400" },
  error_signature:   { bg: "bg-red-950",     border: "border-red-500",     text: "text-red-100",     dot: "bg-red-500" },
  fix_pattern:       { bg: "bg-green-950",   border: "border-green-400",   text: "text-green-100",   dot: "bg-green-400" },
  case_outcome:      { bg: "bg-stone-800",   border: "border-stone-400",   text: "text-stone-100",   dot: "bg-stone-400" },
  entity_term:       { bg: "bg-zinc-800",    border: "border-zinc-500",    text: "text-zinc-100",    dot: "bg-zinc-500" },
};

export const edgeColors: Record<string, { stroke: string; dasharray?: string }> = {
  belongs_to:          { stroke: "#818cf8", dasharray: "5 5" },
  trigger_of:          { stroke: "#fbbf24" },
  involved_in:         { stroke: "#34d399" },
  discovered_in:       { stroke: "#fb7185" },
  causes:              { stroke: "#fb923c" },
  derived_from:        { stroke: "#38bdf8", dasharray: "5 5" },
  affects:             { stroke: "#a78bfa" },
  mentions_identity:   { stroke: "#2dd4bf", dasharray: "3 3" },
  references_identity: { stroke: "#2dd4bf" },
  contradicts:         { stroke: "#f43f5e", dasharray: "8 4" },
  executed_playbook:   { stroke: "#06b6d4" },
  approved_by:         { stroke: "#22c55e" },
  denied_by:           { stroke: "#ef4444", dasharray: "6 3" },
  execution_outcome:   { stroke: "#84cc16" },
  records_decision:    { stroke: "#a855f7", dasharray: "4 4" },
  records_action_on:   { stroke: "#d946ef", dasharray: "4 4" },
  based_on:            { stroke: "#f59e0b" },
  considered:          { stroke: "#fbbf24", dasharray: "4 4" },
  chose:               { stroke: "#f59e0b" },
  applied_policy:      { stroke: "#8b5cf6", dasharray: "5 5" },
  required_approval:   { stroke: "#eab308", dasharray: "6 3" },
  resulted_in:         { stroke: "#f97316" },
  followed_by:         { stroke: "#d97706", dasharray: "8 4" },
  supported_by:        { stroke: "#22c55e" },
  contradicted_by:     { stroke: "#ef4444", dasharray: "8 4" },
  weakened_by:         { stroke: "#f97316", dasharray: "5 4" },
  supported_by_claim:  { stroke: "#ec4899" },
  asserted_in:         { stroke: "#06b6d4", dasharray: "4 4" },
  has_execution:       { stroke: "#84cc16" },
  executes:            { stroke: "#10b981" },
  requires_approval:   { stroke: "#eab308", dasharray: "6 3" },
  involves_user:       { stroke: "#d946ef" },
  targets_workflow:    { stroke: "#14b8a6" },
  tracks_request:      { stroke: "#0ea5e9" },
  runs_on_agent:       { stroke: "#8b5cf6" },
  governs:             { stroke: "#3b82f6", dasharray: "5 3" },
  applies_to:          { stroke: "#2dd4bf" },
  aggregated_by:       { stroke: "#f43f5e" },
  addresses:           { stroke: "#22c55e" },
  recommends:          { stroke: "#38bdf8" },
  validated_fix:       { stroke: "#4ade80" },
  invalidated_fix:     { stroke: "#fb7185", dasharray: "7 3" },
  superseded_by:       { stroke: "#a1a1aa", dasharray: "4 4" },
  modified_by:         { stroke: "#f59e0b", dasharray: "4 3" },
};

export function getNodeClassName(nodeType: string): string {
  const c = nodeColors[nodeType];
  if (!c) return "bg-slate-800 border-slate-600 text-slate-100";
  return `${c.bg} ${c.border} ${c.text}`;
}
