export const NODE_TYPE_OPTIONS = [
  "pattern",
  "episode",
  "playbook",
  "evidence",
  "identity",
  "trigger",
  "entity",
  "error",
  "root_cause",
  "session",
  "execution_run",
  "approval_request",
  "user",
  "decision",
  "decision_option",
  "decision_outcome",
  "tenant_policy",
  "action_policy",
  "claim",
  "error_signature",
  "fix_pattern",
  "case_outcome",
  "entity_term",
] as const;

export const MAF_NODE_TYPE_OPTIONS = [
  "session",
  "decision",
  "decision_option",
  "decision_outcome",
  "approval_request",
  "execution_run",
  "playbook",
  "pattern",
  "episode",
  "evidence",
  "identity",
  "entity",
  "user",
  "tenant_policy",
  "action_policy",
  "claim",
  "error_signature",
  "fix_pattern",
  "case_outcome",
] as const;

export const nodeColors: Record<
  string,
  { bg: string; border: string; text: string; dot: string }
> = {
  pattern:           { bg: "bg-card", border: "border-sky-500",      text: "text-foreground", dot: "bg-sky-500" },
  episode:           { bg: "bg-card", border: "border-emerald-500",  text: "text-foreground", dot: "bg-emerald-500" },
  playbook:          { bg: "bg-card", border: "border-cyan-500",     text: "text-foreground", dot: "bg-cyan-500" },
  identity:          { bg: "bg-card", border: "border-teal-500",     text: "text-foreground", dot: "bg-teal-500" },
  evidence:          { bg: "bg-card", border: "border-slate-500",    text: "text-foreground", dot: "bg-slate-500" },
  trigger:           { bg: "bg-card", border: "border-amber-500",    text: "text-foreground", dot: "bg-amber-500" },
  entity:            { bg: "bg-card", border: "border-lime-500",     text: "text-foreground", dot: "bg-lime-500" },
  error:             { bg: "bg-card", border: "border-rose-500",     text: "text-foreground", dot: "bg-rose-500" },
  root_cause:        { bg: "bg-card", border: "border-yellow-500",   text: "text-foreground", dot: "bg-yellow-500" },
  session:           { bg: "bg-card", border: "border-cyan-500",     text: "text-foreground", dot: "bg-cyan-500" },
  execution_run:     { bg: "bg-card", border: "border-green-500",    text: "text-foreground", dot: "bg-green-500" },
  approval_request:  { bg: "bg-card", border: "border-amber-500",    text: "text-foreground", dot: "bg-amber-500" },
  user:              { bg: "bg-card", border: "border-pink-500",     text: "text-foreground", dot: "bg-pink-500" },
  decision:          { bg: "bg-card", border: "border-amber-500",    text: "text-foreground", dot: "bg-amber-500" },
  decision_option:   { bg: "bg-card", border: "border-yellow-500",   text: "text-foreground", dot: "bg-yellow-500" },
  decision_outcome:  { bg: "bg-card", border: "border-rose-500",     text: "text-foreground", dot: "bg-rose-500" },
  tenant_policy:     { bg: "bg-card", border: "border-violet-500",   text: "text-foreground", dot: "bg-violet-500" },
  action_policy:     { bg: "bg-card", border: "border-blue-500",     text: "text-foreground", dot: "bg-blue-500" },
  claim:             { bg: "bg-card", border: "border-pink-500",     text: "text-foreground", dot: "bg-pink-500" },
  error_signature:   { bg: "bg-card", border: "border-red-500",      text: "text-foreground", dot: "bg-red-500" },
  fix_pattern:       { bg: "bg-card", border: "border-green-500",    text: "text-foreground", dot: "bg-green-500" },
  case_outcome:      { bg: "bg-card", border: "border-stone-500",    text: "text-foreground", dot: "bg-stone-500" },
  entity_term:       { bg: "bg-card", border: "border-zinc-500",     text: "text-foreground", dot: "bg-zinc-500" },
};

export const edgeColors: Record<string, { stroke: string; dasharray?: string }> = {
  belongs_to:          { stroke: "#818cf8", dasharray: "5 5" },
  trigger_of:          { stroke: "#fbbf24" },
  involved_in:         { stroke: "#34d399" },
  discovered_in:       { stroke: "#fb7185" },
  causes:              { stroke: "#fb923c" },
  derived_from:        { stroke: "#38bdf8", dasharray: "5 5" },
  affects:             { stroke: "#a78bfa" },
  mentions_identity:   { stroke: "#2dd4bf", dasharray: "3 3" },
  references_identity: { stroke: "#2dd4bf" },
  contradicts:         { stroke: "#f43f5e", dasharray: "8 4" },
  executed_playbook:   { stroke: "#06b6d4" },
  approved_by:         { stroke: "#22c55e" },
  denied_by:           { stroke: "#ef4444", dasharray: "6 3" },
  execution_outcome:   { stroke: "#84cc16" },
  records_decision:    { stroke: "#a855f7", dasharray: "4 4" },
  records_action_on:   { stroke: "#d946ef", dasharray: "4 4" },
  based_on:            { stroke: "#f59e0b" },
  considered:          { stroke: "#fbbf24", dasharray: "4 4" },
  chose:               { stroke: "#f59e0b" },
  applied_policy:      { stroke: "#8b5cf6", dasharray: "5 5" },
  required_approval:   { stroke: "#eab308", dasharray: "6 3" },
  resulted_in:         { stroke: "#f97316" },
  followed_by:         { stroke: "#d97706", dasharray: "8 4" },
  supported_by:        { stroke: "#22c55e" },
  contradicted_by:     { stroke: "#ef4444", dasharray: "8 4" },
  weakened_by:         { stroke: "#f97316", dasharray: "5 4" },
  supported_by_claim:  { stroke: "#ec4899" },
  asserted_in:         { stroke: "#06b6d4", dasharray: "4 4" },
  has_execution:       { stroke: "#84cc16" },
  executes:            { stroke: "#10b981" },
  requires_approval:   { stroke: "#eab308", dasharray: "6 3" },
  involves_user:       { stroke: "#d946ef" },
  targets_workflow:    { stroke: "#14b8a6" },
  tracks_request:      { stroke: "#0ea5e9" },
  runs_on_agent:       { stroke: "#8b5cf6" },
  governs:             { stroke: "#3b82f6", dasharray: "5 3" },
  applies_to:          { stroke: "#2dd4bf" },
  aggregated_by:       { stroke: "#f43f5e" },
  addresses:           { stroke: "#22c55e" },
  recommends:          { stroke: "#38bdf8" },
  validated_fix:       { stroke: "#4ade80" },
  invalidated_fix:     { stroke: "#fb7185", dasharray: "7 3" },
  superseded_by:       { stroke: "#a1a1aa", dasharray: "4 4" },
  modified_by:         { stroke: "#f59e0b", dasharray: "4 3" },
};

export function getNodeClassName(nodeType: string): string {
  const c = nodeColors[nodeType];
  if (!c) return "bg-card border-border text-foreground";
  return `${c.bg} ${c.border} ${c.text} shadow-sm`;
}

/** Fixed box on hover/select so edge handles do not jump. */
export const GRAPH_NODE_CARD_CLASS =
  "graph-node-card box-border px-4 py-2 border-2 rounded-lg text-sm cursor-pointer";
